### ISSUE TITLE
Review 1: Daigram alir dan realisasi program berbeda

### ISSUE THREAD

**Issue by priyandari** [TimothyGunungTua/UAS-ProgKom-2020#2]
Mohon cek alur kerja program dan kesesuaian program yang telah dibuat. Lengkapi dan lanjutkan program agar lebih baik

**Comment by noviyaadin** [comment]
Diagram alir telah diperbaiki dan dilengkapi sesuai dengan program dan alur kerja program yang telah dibuat

**Comment by priyandari** [comment]
Ok
