### ISSUE TITLE
Review 1: Alur kerja program lebih logis

### ISSUE THREAD

**Issue by priyandari** [TimothyGunungTua/UAS-ProgKom-2020#3]
Perhatikan program
![Capture5](https://user-images.githubusercontent.com/4914090/83827006-823f0800-a707-11ea-8aea-30996b78a850.PNG)

Sudah input jumlah hewan 3
Apabila setipa hewan ingin layanan berbeda-beda bagaimana ?

**Comment by priyandari** [comment]
Perbaiki juga BAHASA yang digunakan dalam perintah dalam pinputan program

**Comment by Talithanaa** [comment]
Program sudat dapat menginput fasilitas yang berbeda untuk setiap hewan, dan untuk menginput jumlah hewan dijalankan setelah menginput fasilitas.
