### ISSUE TITLE
Nota pelayanan

### ISSUE THREAD

**Issue by priyandari** [TimothyGunungTua/UAS-ProgKom-2020#4]
tambahkan nota pelayanan yang harus dibayar.
Misal, untuk kucing, mendapat 2 kucing layanan vaksin, 1 kucing tadi di grooming

No  Layanan         Jenis   Harga/layanan       Kuantitas     Total
1.     Vaksin          Kuc          X                        2                    x*2
2.     Grooming     Kuc          Y                         1                    Y*1
3.     Vaksin          Anj           Z                         2                   Z*2

TOTAL HARUS DIBAYARKAN                                            NAH INI

**Comment by Talithanaa** [comment]
Program telah di tambahkan nota atau billing pelayanan yang harus dibayar.
